#! /bin/sh


# replace-gauche-string.pl
cat debian/control.in > debian/control

#GAUCHE_VERSION=$(gauche-config -V|sed -e 's/_/-/');
#make -f debian/rules  debian/control
#mv debian/gauche-bdb.install debian/gauche-$GAUCHE_VERSION-bdb.install
